name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy to EC2 Instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          EC2_USER: ${{ secrets.USER_NAME }}
          APP_DIR: /var/www/html
          APP_FILE: programa.py
          ENVIRONMENT: production
     
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} << 'EOF'
              # Acceder al directorio del proyecto
              cd /var/www/html && ls &&
              
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&

              # Activar el entorno virtual
              sudo systemctl start apache2
             
          EOF
